version : "2"

services:
    mongo:
      image: mongo:3.6.0
      ports:
       - "27017:27017"
      volumes_from: 
       - mongodata
    mongodata:
      image: tianon/true
      volumes: 
       - /data/db
      #command: echo 'Data Container for Mongo' 
    application:
      build:  
        context: .
      image : chetansindhe/application:kubeint
      command: node /src/bin/www    
      ports:
       - "3000:3000"
      volumes :
      - ./:/src
      links:
       - mongo