apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-a
  labels:
    name: mongo-svc-a
spec:
  type: LoadBalancer
  ports:  
  - port: 27017
    targetPort: 27017    
    protocol: TCP
    name: mongo-svc-a
  selector:
    name: mongo-node1
    instance: rod
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-b
  labels:
    name: mongo-svc-b
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-b
  selector:
    name: mongo-node2
    instance: rod2
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-c
  labels:
    name: mongo-svc-c
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-c
  selector:
    name: mongo-node3
    instance: rod3
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: mongo-rc1 
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-node1
  template:
    metadata:
      labels:
        name: mongo-node1
        instance: rod
    spec:
      containers:
      - name: mongo-node1
        image: mongo:3.6.0
        command:
        - mongod
        - "--replSet"
        - my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage1
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage1
        hostPath:
          path: /data
          type: Directory
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: mongo-rc2 
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-node2
  template:
    metadata:
      labels:
        name: mongo-node2
        instance: rod2
    spec:
      containers:
      - name: mongo-node2
        image: mongo:3.6.0
        command:
        - mongod
        - "--replSet"
        - my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage2
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage2
        hostPath:
          path: /data
          type: Directory
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: mongo-rc3
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-node3
  template:
    metadata:
      labels:
        name: mongo-node3
        instance: rod3
    spec:
      containers:
      - name: mongo-node3
        image: mongo:3.6.0
        command:
        - mongod
        - "--replSet"
        - my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage3
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage3
        hostPath:
          path: /data
          type: Directory